openapi: 3.0.0
info:
  title: SmartCache API
  version: v1
servers:
  - url: http://mowgli-api.winglet.io/smartcache/v1
    description: production server
paths:
  /best_deal:
    post:
      tags:
        - SmartCache
      operationId: bestDeal
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/BestDealRequest"
        required: true
      responses:
        "200":
          description: "Request has been successfully processed"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BestDealResponse"
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "401":
          description: Authentification Failed
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "408":
          description: Request Timeout
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "500":
          description: Server Internal Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
      x-openapi-router-controller: swagger_server.controllers.smart_cache_controller
  /offer_detail/{offer_id}:
    get:
      tags:
        - SmartCache
      operationId: offerDetail
      parameters:
        - name: offer_id
          in: path
          description: Offer ID
          required: true
          style: simple
          explode: false
          schema:
            type: string
      responses:
        "200":
          description: "Request has been successfully processed"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Offer"
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "401":
          description: Authentification Failed
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "404":
          description: Cannot find Offer
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "408":
          description: Request Timeout
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "500":
          description: Server Internal Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
      x-openapi-router-controller: swagger_server.controllers.smart_cache_controller
components:
  schemas:
    BestDealRequest:
      title: BestDealRequest
      required:
        - destination
        - order_by
        - origin
        - outbound_date
        - type
      type: object
      properties:
        origin:
          $ref: "#/components/schemas/RequestOrigin"
        destination:
          $ref: "#/components/schemas/RequestDestination"
        outbound_date:
          $ref: "#/components/schemas/HopDate"
        outbound_time:
          $ref: "#/components/schemas/HopTime"
        inbound_date:
          $ref: "#/components/schemas/HopDate"
        inbound_time:
          $ref: "#/components/schemas/HopTime"
        type:
          $ref: "#/components/schemas/JourneyType"
        tags:
          type: array
          items:
            type: string
        journey_days:
          $ref: "#/components/schemas/JourneyDays"
        max_stopovers:
          type: integer
          format: int64
        hop_duration:
          $ref: "#/components/schemas/HopDuration"
        distance:
          $ref: "#/components/schemas/Distance"
        checked_baggage:
          type: integer
          format: int64
        cabin:
          $ref: "#/components/schemas/CabinType"
        budget:
          type: number
          format: float
        currency:
          $ref: "#/components/schemas/Currency"
        continuation_token:
          type: string
        size:
          type: integer
          format: int64
          default: 20
        order_by:
          $ref: "#/components/schemas/BestDealRequestOrderMetric"
        one_by_destination:
          type: boolean
          default: true
      additionalProperties: false
    BestDealRequestOrderMetric:
      title: BestDealRequestOrderMetric
      type: string
      default: POPULARITY
      enum:
        - POPULARITY
        - PRICE
        - FRESHNESS
    BestDealResponse:
      title: BestDealResponse
      type: object
      properties:
        offers:
          type: array
          items:
            $ref: "#/components/schemas/Offer"
        tags:
          type: array
          items:
            $ref: "#/components/schemas/Tag"
        continuation_token:
          type: string
      additionalProperties: false
      example:
        offers:
          - service_bundles:
              - traveler_ids:
                  - traveler_ids
                  - traveler_ids
                id: id
                services:
                  - marketing_name: marketing_name
                    name: name
                    description: description
                    attributes:
                      key: attributes
                    id: id
                    type: CABINCLASS
                  - marketing_name: marketing_name
                    name: name
                    description: description
                    attributes:
                      key: attributes
                    id: id
                    type: CABINCLASS
                transport_service_id: transport_service_id
              - traveler_ids:
                  - traveler_ids
                  - traveler_ids
                id: id
                services:
                  - marketing_name: marketing_name
                    name: name
                    description: description
                    attributes:
                      key: attributes
                    id: id
                    type: CABINCLASS
                  - marketing_name: marketing_name
                    name: name
                    description: description
                    attributes:
                      key: attributes
                    id: id
                    type: CABINCLASS
                transport_service_id: transport_service_id
            viewed_at: viewed_at
            total_amount:
              currency: EUR
              value: 9.301444
            hops:
              - stopover_duration: 5
                arrival_time: arrival_time
                departure_date: departure_date
                origin: null
                destination:
                  code: code
                  coordinate:
                    altitude: 0.8008282
                    latitude: 6.0274563
                    longitude: 1.4658129
                  id: id
                  type: AIRPORT
                  code_type: IATA
                type: OUTBOUND
                destination_city:
                  code: code
                  id: id
                  code_type: null
                duration: 5
                origin_city: null
                transport_services:
                  - equipment_name: equipment_name
                    stopover_duration: 7
                    arrival_time: arrival_time
                    departure_date: departure_date
                    origin: null
                    destination: null
                    equipment: equipment
                    operating_designator: operating_designator
                    marketing_designator: marketing_designator
                    operating_carrier: null
                    type: FLIGHT
                    marketing_carrier:
                      code: code
                    duration: 2
                    id: id
                    arrival_date: arrival_date
                    departure_time: departure_time
                  - equipment_name: equipment_name
                    stopover_duration: 7
                    arrival_time: arrival_time
                    departure_date: departure_date
                    origin: null
                    destination: null
                    equipment: equipment
                    operating_designator: operating_designator
                    marketing_designator: marketing_designator
                    operating_carrier: null
                    type: FLIGHT
                    marketing_carrier:
                      code: code
                    duration: 2
                    id: id
                    arrival_date: arrival_date
                    departure_time: departure_time
                id: id
                arrival_date: arrival_date
                departure_time: departure_time
              - stopover_duration: 5
                arrival_time: arrival_time
                departure_date: departure_date
                origin: null
                destination:
                  code: code
                  coordinate:
                    altitude: 0.8008282
                    latitude: 6.0274563
                    longitude: 1.4658129
                  id: id
                  type: AIRPORT
                  code_type: IATA
                type: OUTBOUND
                destination_city:
                  code: code
                  id: id
                  code_type: null
                duration: 5
                origin_city: null
                transport_services:
                  - equipment_name: equipment_name
                    stopover_duration: 7
                    arrival_time: arrival_time
                    departure_date: departure_date
                    origin: null
                    destination: null
                    equipment: equipment
                    operating_designator: operating_designator
                    marketing_designator: marketing_designator
                    operating_carrier: null
                    type: FLIGHT
                    marketing_carrier:
                      code: code
                    duration: 2
                    id: id
                    arrival_date: arrival_date
                    departure_time: departure_time
                  - equipment_name: equipment_name
                    stopover_duration: 7
                    arrival_time: arrival_time
                    departure_date: departure_date
                    origin: null
                    destination: null
                    equipment: equipment
                    operating_designator: operating_designator
                    marketing_designator: marketing_designator
                    operating_carrier: null
                    type: FLIGHT
                    marketing_carrier:
                      code: code
                    duration: 2
                    id: id
                    arrival_date: arrival_date
                    departure_time: departure_time
                id: id
                arrival_date: arrival_date
                departure_time: departure_time
            id: id
            metrics:
              lowest_price: 3.6160767
              average_price: 2.027123
            total_tax: null
            travelers:
              - id: id
                type: ADULT
                service_bundle_ids:
                  - service_bundle_ids
                  - service_bundle_ids
              - id: id
                type: ADULT
                service_bundle_ids:
                  - service_bundle_ids
                  - service_bundle_ids
            tags:
              - tags
              - tags
          - service_bundles:
              - traveler_ids:
                  - traveler_ids
                  - traveler_ids
                id: id
                services:
                  - marketing_name: marketing_name
                    name: name
                    description: description
                    attributes:
                      key: attributes
                    id: id
                    type: CABINCLASS
                  - marketing_name: marketing_name
                    name: name
                    description: description
                    attributes:
                      key: attributes
                    id: id
                    type: CABINCLASS
                transport_service_id: transport_service_id
              - traveler_ids:
                  - traveler_ids
                  - traveler_ids
                id: id
                services:
                  - marketing_name: marketing_name
                    name: name
                    description: description
                    attributes:
                      key: attributes
                    id: id
                    type: CABINCLASS
                  - marketing_name: marketing_name
                    name: name
                    description: description
                    attributes:
                      key: attributes
                    id: id
                    type: CABINCLASS
                transport_service_id: transport_service_id
            viewed_at: viewed_at
            total_amount:
              currency: EUR
              value: 9.301444
            hops:
              - stopover_duration: 5
                arrival_time: arrival_time
                departure_date: departure_date
                origin: null
                destination:
                  code: code
                  coordinate:
                    altitude: 0.8008282
                    latitude: 6.0274563
                    longitude: 1.4658129
                  id: id
                  type: AIRPORT
                  code_type: IATA
                type: OUTBOUND
                destination_city:
                  code: code
                  id: id
                  code_type: null
                duration: 5
                origin_city: null
                transport_services:
                  - equipment_name: equipment_name
                    stopover_duration: 7
                    arrival_time: arrival_time
                    departure_date: departure_date
                    origin: null
                    destination: null
                    equipment: equipment
                    operating_designator: operating_designator
                    marketing_designator: marketing_designator
                    operating_carrier: null
                    type: FLIGHT
                    marketing_carrier:
                      code: code
                    duration: 2
                    id: id
                    arrival_date: arrival_date
                    departure_time: departure_time
                  - equipment_name: equipment_name
                    stopover_duration: 7
                    arrival_time: arrival_time
                    departure_date: departure_date
                    origin: null
                    destination: null
                    equipment: equipment
                    operating_designator: operating_designator
                    marketing_designator: marketing_designator
                    operating_carrier: null
                    type: FLIGHT
                    marketing_carrier:
                      code: code
                    duration: 2
                    id: id
                    arrival_date: arrival_date
                    departure_time: departure_time
                id: id
                arrival_date: arrival_date
                departure_time: departure_time
              - stopover_duration: 5
                arrival_time: arrival_time
                departure_date: departure_date
                origin: null
                destination:
                  code: code
                  coordinate:
                    altitude: 0.8008282
                    latitude: 6.0274563
                    longitude: 1.4658129
                  id: id
                  type: AIRPORT
                  code_type: IATA
                type: OUTBOUND
                destination_city:
                  code: code
                  id: id
                  code_type: null
                duration: 5
                origin_city: null
                transport_services:
                  - equipment_name: equipment_name
                    stopover_duration: 7
                    arrival_time: arrival_time
                    departure_date: departure_date
                    origin: null
                    destination: null
                    equipment: equipment
                    operating_designator: operating_designator
                    marketing_designator: marketing_designator
                    operating_carrier: null
                    type: FLIGHT
                    marketing_carrier:
                      code: code
                    duration: 2
                    id: id
                    arrival_date: arrival_date
                    departure_time: departure_time
                  - equipment_name: equipment_name
                    stopover_duration: 7
                    arrival_time: arrival_time
                    departure_date: departure_date
                    origin: null
                    destination: null
                    equipment: equipment
                    operating_designator: operating_designator
                    marketing_designator: marketing_designator
                    operating_carrier: null
                    type: FLIGHT
                    marketing_carrier:
                      code: code
                    duration: 2
                    id: id
                    arrival_date: arrival_date
                    departure_time: departure_time
                id: id
                arrival_date: arrival_date
                departure_time: departure_time
            id: id
            metrics:
              lowest_price: 3.6160767
              average_price: 2.027123
            total_tax: null
            travelers:
              - id: id
                type: ADULT
                service_bundle_ids:
                  - service_bundle_ids
                  - service_bundle_ids
              - id: id
                type: ADULT
                service_bundle_ids:
                  - service_bundle_ids
                  - service_bundle_ids
            tags:
              - tags
              - tags
        continuation_token: continuation_token
        tags:
          - count: 4
            id: id
          - count: 4
            id: id
    Error:
      title: Error
      type: object
      properties:
        code:
          type: string
        message:
          type: string
      additionalProperties: false
    CalendarRequest:
      title: CalendarRequest
      required:
        - calendar_field
        - destination
        - origin
        - outbound_date
        - type
      type: object
      properties:
        origin:
          $ref: "#/components/schemas/RequestOrigin"
        destination:
          $ref: "#/components/schemas/RequestDestination"
        outbound_date:
          $ref: "#/components/schemas/HopDate"
        outbound_time:
          $ref: "#/components/schemas/HopTime"
        inbound_date:
          $ref: "#/components/schemas/HopDate"
        inbound_time:
          $ref: "#/components/schemas/HopTime"
        type:
          $ref: "#/components/schemas/JourneyType"
        journey_days:
          $ref: "#/components/schemas/JourneyDays"
        max_stopovers:
          type: integer
          format: int64
        hop_duration:
          $ref: "#/components/schemas/HopDuration"
        checked_baggage:
          type: integer
          format: int64
        cabin:
          $ref: "#/components/schemas/CabinType"
        currency:
          $ref: "#/components/schemas/Currency"
        calendar_field:
          $ref: "#/components/schemas/CalendarField"
      additionalProperties: false
    CalendarField:
      type: string
      enum:
        - OUTBOUND_DEPARTURE_DATE
        - INBOUND_DEPARTURE_DATE
    CalendarResponse:
      title: CalendarResponse
      type: object
      properties:
        calendar_cells:
          type: array
          items:
            $ref: "#/components/schemas/CalendarCell"
      additionalProperties: false
      example:
        calendar_cells:
          - amount:
              currency: EUR
              value: 9.301444
            inbound_departure_date: inbound_departure_date
            outbound_departure_date: outbound_departure_date
            offer_id: offer_id
          - amount:
              currency: EUR
              value: 9.301444
            inbound_departure_date: inbound_departure_date
            outbound_departure_date: outbound_departure_date
            offer_id: offer_id
    Offer:
      title: Offer
      type: object
      properties:
        hops:
          type: array
          items:
            $ref: "#/components/schemas/Hop"
        id:
          type: string
        service_bundles:
          type: array
          items:
            $ref: "#/components/schemas/ServiceBundle"
        total_amount:
          $ref: "#/components/schemas/Amount"
        total_tax:
          $ref: "#/components/schemas/Amount"
        travelers:
          type: array
          items:
            $ref: "#/components/schemas/Traveler"
        viewed_at:
          type: string
        metrics:
          $ref: "#/components/schemas/Metrics"
        tags:
          type: array
          items:
            type: string
      additionalProperties: false
      example:
        service_bundles:
          - traveler_ids:
              - traveler_ids
              - traveler_ids
            id: id
            services:
              - marketing_name: marketing_name
                name: name
                description: description
                attributes:
                  key: attributes
                id: id
                type: CABINCLASS
              - marketing_name: marketing_name
                name: name
                description: description
                attributes:
                  key: attributes
                id: id
                type: CABINCLASS
            transport_service_id: transport_service_id
          - traveler_ids:
              - traveler_ids
              - traveler_ids
            id: id
            services:
              - marketing_name: marketing_name
                name: name
                description: description
                attributes:
                  key: attributes
                id: id
                type: CABINCLASS
              - marketing_name: marketing_name
                name: name
                description: description
                attributes:
                  key: attributes
                id: id
                type: CABINCLASS
            transport_service_id: transport_service_id
        viewed_at: viewed_at
        total_amount:
          currency: EUR
          value: 9.301444
        hops:
          - stopover_duration: 5
            arrival_time: arrival_time
            departure_date: departure_date
            origin: null
            destination:
              code: code
              coordinate:
                altitude: 0.8008282
                latitude: 6.0274563
                longitude: 1.4658129
              id: id
              type: AIRPORT
              code_type: IATA
            type: OUTBOUND
            destination_city:
              code: code
              id: id
              code_type: null
            duration: 5
            origin_city: null
            transport_services:
              - equipment_name: equipment_name
                stopover_duration: 7
                arrival_time: arrival_time
                departure_date: departure_date
                origin: null
                destination: null
                equipment: equipment
                operating_designator: operating_designator
                marketing_designator: marketing_designator
                operating_carrier: null
                type: FLIGHT
                marketing_carrier:
                  code: code
                duration: 2
                id: id
                arrival_date: arrival_date
                departure_time: departure_time
              - equipment_name: equipment_name
                stopover_duration: 7
                arrival_time: arrival_time
                departure_date: departure_date
                origin: null
                destination: null
                equipment: equipment
                operating_designator: operating_designator
                marketing_designator: marketing_designator
                operating_carrier: null
                type: FLIGHT
                marketing_carrier:
                  code: code
                duration: 2
                id: id
                arrival_date: arrival_date
                departure_time: departure_time
            id: id
            arrival_date: arrival_date
            departure_time: departure_time
          - stopover_duration: 5
            arrival_time: arrival_time
            departure_date: departure_date
            origin: null
            destination:
              code: code
              coordinate:
                altitude: 0.8008282
                latitude: 6.0274563
                longitude: 1.4658129
              id: id
              type: AIRPORT
              code_type: IATA
            type: OUTBOUND
            destination_city:
              code: code
              id: id
              code_type: null
            duration: 5
            origin_city: null
            transport_services:
              - equipment_name: equipment_name
                stopover_duration: 7
                arrival_time: arrival_time
                departure_date: departure_date
                origin: null
                destination: null
                equipment: equipment
                operating_designator: operating_designator
                marketing_designator: marketing_designator
                operating_carrier: null
                type: FLIGHT
                marketing_carrier:
                  code: code
                duration: 2
                id: id
                arrival_date: arrival_date
                departure_time: departure_time
              - equipment_name: equipment_name
                stopover_duration: 7
                arrival_time: arrival_time
                departure_date: departure_date
                origin: null
                destination: null
                equipment: equipment
                operating_designator: operating_designator
                marketing_designator: marketing_designator
                operating_carrier: null
                type: FLIGHT
                marketing_carrier:
                  code: code
                duration: 2
                id: id
                arrival_date: arrival_date
                departure_time: departure_time
            id: id
            arrival_date: arrival_date
            departure_time: departure_time
        id: id
        metrics:
          lowest_price: 3.6160767
          average_price: 2.027123
        total_tax: null
        travelers:
          - id: id
            type: ADULT
            service_bundle_ids:
              - service_bundle_ids
              - service_bundle_ids
          - id: id
            type: ADULT
            service_bundle_ids:
              - service_bundle_ids
              - service_bundle_ids
        tags:
          - tags
          - tags
    RequestOrigin:
      title: RequestOrigin
      required:
        - type
      type: object
      properties:
        codes:
          type: array
          items:
            type: string
        code_type:
          $ref: "#/components/schemas/CodeType"
        type:
          $ref: "#/components/schemas/RequestOriginType"
      additionalProperties: false
    RequestDestination:
      title: RequestDestination
      required:
        - type
      type: object
      properties:
        codes:
          minItems: 1
          type: array
          items:
            type: string
        code_type:
          $ref: "#/components/schemas/CodeType"
        type:
          $ref: "#/components/schemas/RequestDestinationType"
      additionalProperties: false
    HopDate:
      title: HopDate
      type: object
      properties:
        fixed_date:
          $ref: "#/components/schemas/FixedDate"
        flexible_date:
          $ref: "#/components/schemas/FlexibleDate"
        type:
          $ref: "#/components/schemas/HopDateType"
      additionalProperties: false
    FixedDate:
      title: FixedDate
      required:
        - date
      type: object
      properties:
        date:
          type: string
        plus_minus:
          type: integer
          format: int64
      additionalProperties: false
    HopDateType:
      title: HopDateType
      type: string
      enum:
        - DEPARTURE
        - ARRIVAL
    HopTime:
      title: HopTime
      type: object
      properties:
        flexible_time:
          $ref: "#/components/schemas/FlexibleTime"
        time:
          type: string
        type:
          $ref: "#/components/schemas/HopTimeType"
      additionalProperties: false
    FlexibleTime:
      title: FlexibleTime
      type: object
      properties:
        max:
          type: string
        min:
          type: string
      additionalProperties: false
    HopTimeType:
      title: HopTimeType
      type: string
      enum:
        - DEPARTURE
        - ARRIVAL
    JourneyType:
      title: JourneyType
      type: string
      default: ROUNDTRIP
      enum:
        - ONEWAY
        - ROUNDTRIP
    JourneyDays:
      title: JourneyDays
      type: object
      properties:
        flexible_journey_days:
          $ref: "#/components/schemas/FlexibleJourneyDays"
        journey_days:
          type: integer
          format: int64
      additionalProperties: false
    HopDuration:
      title: HopDuration
      type: object
      properties:
        max:
          type: integer
          format: int64
        min:
          type: integer
          format: int64
      additionalProperties: false
    Distance:
      title: Distance
      type: object
      properties:
        max:
          type: integer
          format: int64
        min:
          type: integer
          format: int64
      additionalProperties: false
    CabinType:
      title: CabinType
      type: string
      enum:
        - ECONOMY
        - PREMIUM
        - BUSINESS
        - FIRST
    Currency:
      title: Currency
      type: string
      default: EUR
      enum:
        - EUR
    Tag:
      title: Tag
      type: object
      properties:
        id:
          type: string
        count:
          type: integer
      additionalProperties: false
      example:
        count: 4
        id: id
    CalendarCell:
      title: CalendarCell
      type: object
      properties:
        amount:
          $ref: "#/components/schemas/Amount"
        inbound_departure_date:
          type: string
        offer_id:
          type: string
        outbound_departure_date:
          type: string
      additionalProperties: false
      example:
        amount:
          currency: EUR
          value: 9.301444
        inbound_departure_date: inbound_departure_date
        outbound_departure_date: outbound_departure_date
        offer_id: offer_id
    Hop:
      title: Hop
      type: object
      properties:
        arrival_date:
          type: string
        arrival_time:
          type: string
        departure_date:
          type: string
        departure_time:
          type: string
        destination:
          $ref: "#/components/schemas/Location"
        destination_city:
          $ref: "#/components/schemas/City"
        duration:
          type: integer
          format: int64
        id:
          type: string
        origin:
          $ref: "#/components/schemas/Location"
        origin_city:
          $ref: "#/components/schemas/City"
        stopover_duration:
          type: integer
          format: int64
        transport_services:
          type: array
          items:
            $ref: "#/components/schemas/TransportService"
        type:
          $ref: "#/components/schemas/HopType"
      additionalProperties: false
      example:
        stopover_duration: 5
        arrival_time: arrival_time
        departure_date: departure_date
        origin: null
        destination:
          code: code
          coordinate:
            altitude: 0.8008282
            latitude: 6.0274563
            longitude: 1.4658129
          id: id
          type: AIRPORT
          code_type: IATA
        type: OUTBOUND
        destination_city:
          code: code
          id: id
          code_type: null
        duration: 5
        origin_city: null
        transport_services:
          - equipment_name: equipment_name
            stopover_duration: 7
            arrival_time: arrival_time
            departure_date: departure_date
            origin: null
            destination: null
            equipment: equipment
            operating_designator: operating_designator
            marketing_designator: marketing_designator
            operating_carrier: null
            type: FLIGHT
            marketing_carrier:
              code: code
            duration: 2
            id: id
            arrival_date: arrival_date
            departure_time: departure_time
          - equipment_name: equipment_name
            stopover_duration: 7
            arrival_time: arrival_time
            departure_date: departure_date
            origin: null
            destination: null
            equipment: equipment
            operating_designator: operating_designator
            marketing_designator: marketing_designator
            operating_carrier: null
            type: FLIGHT
            marketing_carrier:
              code: code
            duration: 2
            id: id
            arrival_date: arrival_date
            departure_time: departure_time
        id: id
        arrival_date: arrival_date
        departure_time: departure_time
    HopType:
      title: HopType
      type: string
      enum:
        - OUTBOUND
        - INBOUND
    ServiceBundle:
      title: ServiceBundle
      type: object
      properties:
        id:
          type: string
        services:
          type: array
          items:
            $ref: "#/components/schemas/Service"
        transport_service_id:
          type: string
        traveler_ids:
          type: array
          items:
            type: string
      additionalProperties: false
      example:
        traveler_ids:
          - traveler_ids
          - traveler_ids
        id: id
        services:
          - marketing_name: marketing_name
            name: name
            description: description
            attributes:
              key: attributes
            id: id
            type: CABINCLASS
          - marketing_name: marketing_name
            name: name
            description: description
            attributes:
              key: attributes
            id: id
            type: CABINCLASS
        transport_service_id: transport_service_id
    Amount:
      title: Amount
      required:
        - currency
        - value
      type: object
      properties:
        currency:
          $ref: "#/components/schemas/Currency"
        value:
          type: number
          format: float
      additionalProperties: false
      example:
        currency: EUR
        value: 9.301444
    Traveler:
      title: Traveler
      type: object
      properties:
        id:
          type: string
        service_bundle_ids:
          type: array
          items:
            type: string
        type:
          $ref: "#/components/schemas/TravelerType"
      additionalProperties: false
      example:
        id: id
        type: ADULT
        service_bundle_ids:
          - service_bundle_ids
          - service_bundle_ids
    Metrics:
      title: Metrics
      type: object
      properties:
        lowest_price:
          title: LowestPrice
          type: number
          format: float
        average_price:
          title: AveragePrice
          type: number
          format: float
      additionalProperties: false
      example:
        lowest_price: 3.6160767
        average_price: 2.027123
    CodeType:
      title: CodeType
      type: string
      enum:
        - IATA
        - ISO3316
        - IPv4
        - IPv6
        - MowgliCategory
        - CustomCategory
    RequestOriginType:
      title: RequestLocationType
      type: string
      enum:
        - AIRPORT
        - CITY
    RequestDestinationType:
      title: RequestLocationType
      type: string
      enum:
        - AIRPORT
        - CITY
        - OPEN
    FlexibleDate:
      title: FlexibleDate
      required:
        - type
      type: object
      properties:
        days_of_week:
          type: array
          items:
            $ref: "#/components/schemas/DayOfWeek"
        max:
          type: string
        min:
          type: string
        type:
          $ref: "#/components/schemas/FlexibleDateType"
      additionalProperties: false
    DayOfWeek:
      title: DayOfWeek
      type: string
      enum:
        - MONDAY
        - TUESDAY
        - WEDNESDAY
        - THURSDAY
        - FRIDAY
        - SATURDAY
        - SUNDAY
    FlexibleDateType:
      title: FlexibleDateType
      type: string
      enum:
        - OPEN
        - RANGE
    FlexibleJourneyDays:
      title: FlexibleJourneyDays
      type: object
      properties:
        max:
          type: integer
          format: int64
        min:
          type: integer
          format: int64
      additionalProperties: false
    Location:
      title: Location
      type: object
      properties:
        id:
          type: string
        type:
          $ref: "#/components/schemas/LocationType"
        code:
          type: string
        code_type:
          $ref: "#/components/schemas/CodeType"
        coordinate:
          $ref: "#/components/schemas/Coordinate"
      additionalProperties: false
      example:
        code: code
        coordinate:
          altitude: 0.8008282
          latitude: 6.0274563
          longitude: 1.4658129
        id: id
        type: AIRPORT
        code_type: IATA
    LocationType:
      title: LocationType
      type: string
      enum:
        - AIRPORT
        - TRAINSTATION
        - FURRY
        - UNKNOWN
    City:
      title: City
      type: object
      properties:
        id:
          type: string
        code:
          type: string
        code_type:
          $ref: "#/components/schemas/CodeType"
      additionalProperties: false
      example:
        code: code
        id: id
        code_type: null
    TransportService:
      title: TransportService
      type: object
      properties:
        arrival_date:
          type: string
        arrival_time:
          type: string
        departure_date:
          type: string
        departure_time:
          type: string
        destination:
          $ref: "#/components/schemas/Location"
        duration:
          type: integer
          format: int64
        equipment:
          type: string
        equipment_name:
          type: string
        id:
          type: string
        marketing_carrier:
          $ref: "#/components/schemas/Carrier"
        marketing_designator:
          type: string
        operating_carrier:
          $ref: "#/components/schemas/Carrier"
        operating_designator:
          type: string
        origin:
          $ref: "#/components/schemas/Location"
        stopover_duration:
          type: integer
          format: int64
        type:
          $ref: "#/components/schemas/TransportServiceType"
      additionalProperties: false
      example:
        equipment_name: equipment_name
        stopover_duration: 7
        arrival_time: arrival_time
        departure_date: departure_date
        origin: null
        destination: null
        equipment: equipment
        operating_designator: operating_designator
        marketing_designator: marketing_designator
        operating_carrier: null
        type: FLIGHT
        marketing_carrier:
          code: code
        duration: 2
        id: id
        arrival_date: arrival_date
        departure_time: departure_time
    Service:
      title: Service
      type: object
      properties:
        attributes:
          type: object
          additionalProperties:
            type: string
        description:
          type: string
        id:
          type: string
        marketing_name:
          type: string
        name:
          type: string
        type:
          $ref: "#/components/schemas/ServiceType"
      additionalProperties: false
      example:
        marketing_name: marketing_name
        name: name
        description: description
        attributes:
          key: attributes
        id: id
        type: CABINCLASS
    TravelerType:
      title: TravelerType
      type: string
      enum:
        - ADULT
        - CHILD
        - INFANT
    Coordinate:
      title: Coordinate
      type: object
      properties:
        altitude:
          type: number
          format: float
        latitude:
          type: number
          format: float
        longitude:
          type: number
          format: float
      additionalProperties: false
      example:
        altitude: 0.8008282
        latitude: 6.0274563
        longitude: 1.4658129
    Carrier:
      title: Carrier
      type: object
      properties:
        code:
          type: string
      additionalProperties: false
      example:
        code: code
    TransportServiceType:
      title: TransportServiceType
      type: string
      enum:
        - FLIGHT
        - TRAIN
    ServiceType:
      title: ServiceType
      type: string
      enum:
        - CABINCLASS
        - BAGGAGE
        - OTHER
